refactored

diff --git a/bin/hosts-gen b/bin/hosts-gen
--- a/bin/hosts-gen
+++ b/bin/hosts-gen
@@ -1,20 +1,30 @@
 #!/bin/sh
 # See the LICENSE file for copyright and license details.
 
-etcdir="/etc/hosts.d"
-hostsfile="/etc/hosts"
-
-hostfiles="$(ls -1 "${etcdir}" | grep '^[0-9]*-.*')"
+hosts="/etc/hosts"
+hostsdir="/etc/hosts.d"
+urls="${hostsdir}/urls"
 
 [ $(id -u ) -ne 0 ] && printf "Please run as root.\n" && exit 1
+[ ! -d "$hostsdir" ] && printf "%s not found.\n" "$hostsdir" && exit 1
+[ ! -f "$urls" ] && printf "%s not found.\n" "$urls" && exit 1
+[ -n "$1" ] && startind="$1" || startind=0
 
-[ -e "$hostsfile" ] && cp "$hostsfile" "$hostsfile.bkp"
+while IFS=' ' read -r url ident; do
+    case "$url" in
+        "#"*) : ;;
+        *) [ "${#startind}" -lt 10 ] && ind="0${startind}" || ind="${startind}"
+            startind=$((startind+1))
+            curl "$url" > "${hostsdir}/${ind}-hosts${ident:+.$ident}" ;;
+    esac
+done < "$urls"
 
-truncate -s 0 "${hostsfile}"
-for f in $hostfiles;
-do
-	cat "${etcdir}/${f}" >> "${hostsfile}"
+[ -e "$hosts" ] && cp "$hosts" "$hosts.bkp"
+truncate -s 0 "${hosts}"
+
+hostfiles="$(find "${hostsdir}" -type f | grep -v "^${urls}$" | sort)"
+for file in $hostfiles; do
+	cat "$file" >> "${hosts}"
 done
 
-printf "%s file created.\n" "${hostsfile}"
-
+# vim ft=sh
